"""Initial baseline migration

Revision ID: e84046355001
Revises: 
Create Date: 2026-07-21 15:12:44.302391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84046355001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('official_url', sa.String(), nullable=False),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schemes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_schemes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schemes_title'), ['title'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('weather_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('disease_risk', sa.String(), nullable=True),
    sa.Column('pest_risk', sa.String(), nullable=True),
    sa.Column('water_stress', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_logs_location'), ['location'], unique=False)

    op.create_table('crop_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('recommended_crop', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('top_recommendations', sa.JSON(), nullable=True),
    sa.Column('model_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_predictions_id'), ['id'], unique=False)

    op.create_table('disease_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('disease_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('treatment_plan', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disease_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disease_predictions_id'), ['id'], unique=False)

    op.create_table('fertilizer_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('recommended_fertilizer', sa.String(), nullable=False),
    sa.Column('organic_alternative', sa.String(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fertilizer_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fertilizer_predictions_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('pest_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('pest_name', sa.String(), nullable=False),
    sa.Column('pest_count', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('treatment_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pest_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pest_predictions_id'), ['id'], unique=False)

    op.create_table('scheme_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('bookmarked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheme_bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_bookmarks_id'), ['id'], unique=False)

    op.create_table('soil_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('organic_carbon', sa.Float(), nullable=True),
    sa.Column('fertility_level', sa.String(), nullable=False),
    sa.Column('shap_explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soil_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soil_predictions_id'), ['id'], unique=False)

    op.create_table('yield_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('yield_tons_per_ha', sa.Float(), nullable=False),
    sa.Column('total_production_tons', sa.Float(), nullable=False),
    sa.Column('estimated_revenue_inr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yield_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yield_predictions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yield_predictions_id'))

    op.drop_table('yield_predictions')
    with op.batch_alter_table('soil_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soil_predictions_id'))

    op.drop_table('soil_predictions')
    with op.batch_alter_table('scheme_bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_bookmarks_id'))

    op.drop_table('scheme_bookmarks')
    with op.batch_alter_table('pest_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pest_predictions_id'))

    op.drop_table('pest_predictions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('fertilizer_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fertilizer_predictions_id'))

    op.drop_table('fertilizer_predictions')
    with op.batch_alter_table('disease_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disease_predictions_id'))

    op.drop_table('disease_predictions')
    with op.batch_alter_table('crop_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_predictions_id'))

    op.drop_table('crop_predictions')
    with op.batch_alter_table('weather_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_logs_location'))
        batch_op.drop_index(batch_op.f('ix_weather_logs_id'))

    op.drop_table('weather_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_id'))

    op.drop_table('system_logs')
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schemes_title'))
        batch_op.drop_index(batch_op.f('ix_schemes_id'))
        batch_op.drop_index(batch_op.f('ix_schemes_category'))

    op.drop_table('schemes')
    # ### end Alembic commands ###
